# SPDX-License-Identifier: Apache-2.0
"""Spec 013 — FR-013-01/02/04, AC-1 (in-process HTTPS + WSS), AC-2 (config errors).

The server is started in-process with ``uvicorn.Server`` on a free loopback port and a
certificate generated by ``scripts/selfsigned_cert.py``; the clients skip verification
(self-signed). No network beyond 127.0.0.1 (Constitution Art. XII.2).
"""

from __future__ import annotations

import asyncio
import importlib.util
import logging
import os
import socket
import ssl
import sys
import time
from pathlib import Path

import httpx
import pytest
import uvicorn
from cryptography import x509
from websockets.asyncio.client import connect

from lenguaraz import cli
from lenguaraz.api.app import create_app
from lenguaraz.cli import build_uvicorn_kwargs
from lenguaraz.config import ConfigError, Settings, StagesFile, load_settings
from lenguaraz.models import StatusEvent, parse_event
from lenguaraz.stt.fake import FakeSttEngine

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "selfsigned_cert.py"
spec = importlib.util.spec_from_file_location("selfsigned_cert", SCRIPT)
assert spec and spec.loader
selfsigned_cert = importlib.util.module_from_spec(spec)
sys.modules["selfsigned_cert"] = selfsigned_cert
spec.loader.exec_module(selfsigned_cert)


@pytest.fixture
def cert_pair(tmp_path: Path) -> tuple[Path, Path]:
    return selfsigned_cert.generate_selfsigned(tmp_path / "dev-cert.pem", tmp_path / "dev-key.pem")


# --------------------------------------------------------------------- FR-013-04: the script


def test_selfsigned_certificate_covers_localhost_and_loopback(cert_pair: tuple[Path, Path]) -> None:
    cert_path, key_path = cert_pair
    certificate = x509.load_pem_x509_certificate(cert_path.read_bytes())
    san = certificate.extensions.get_extension_for_class(x509.SubjectAlternativeName).value
    assert san.get_values_for_type(x509.DNSName) == ["localhost"]
    assert {str(ip) for ip in san.get_values_for_type(x509.IPAddress)} == {"127.0.0.1", "::1"}
    lifetime = certificate.not_valid_after_utc - certificate.not_valid_before_utc
    assert 824 <= lifetime.days <= 826
    assert certificate.issuer == certificate.subject  # self-signed
    assert key_path.read_text(encoding="ascii").startswith("-----BEGIN PRIVATE KEY-----")
    if os.name == "posix":
        assert (key_path.stat().st_mode & 0o777) == 0o600


def test_script_main_writes_into_the_requested_folder(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    argv = ["--dir", str(tmp_path / "certs"), "--hostname", "captions.local"]
    assert selfsigned_cert.main(argv) == 0
    assert (tmp_path / "certs" / "dev-cert.pem").is_file()
    assert (tmp_path / "certs" / "dev-key.pem").is_file()
    out = capsys.readouterr().out
    assert "never for production" in out
    assert "TLS_CERT_FILE=" in out


# ------------------------------------------------------------ FR-013-01, AC-2: configuration


def test_cert_without_key_is_a_config_error(cert_pair: tuple[Path, Path]) -> None:
    cert_path, _ = cert_pair
    with pytest.raises(ConfigError, match="TLS_KEY_FILE is not set"):
        load_settings(_env_file=None, engine="fake", tls_cert_file=cert_path)


def test_key_without_cert_is_a_config_error(cert_pair: tuple[Path, Path]) -> None:
    _, key_path = cert_pair
    with pytest.raises(ConfigError, match="TLS_CERT_FILE is not set"):
        load_settings(_env_file=None, engine="fake", tls_key_file=key_path)


def test_missing_certificate_file_is_a_config_error(
    cert_pair: tuple[Path, Path], tmp_path: Path
) -> None:
    _, key_path = cert_pair
    with pytest.raises(ConfigError, match="TLS_CERT_FILE not found"):
        load_settings(
            _env_file=None,
            engine="fake",
            tls_cert_file=tmp_path / "nope.pem",
            tls_key_file=key_path,
        )
    cert_path, _ = cert_pair
    with pytest.raises(ConfigError, match="TLS_CA_FILE not found"):
        load_settings(
            _env_file=None,
            engine="fake",
            tls_cert_file=cert_path,
            tls_key_file=key_path,
            tls_ca_file=tmp_path / "missing-ca.pem",
        )


def test_both_files_enable_tls_and_defaults_stay_plain(cert_pair: tuple[Path, Path]) -> None:
    cert_path, key_path = cert_pair
    plain = Settings(_env_file=None, engine="fake")
    assert plain.tls_enabled is False
    assert plain.proxy_headers is True
    assert plain.forwarded_allow_ips == "127.0.0.1,::1"
    secure = Settings(_env_file=None, engine="fake", tls_cert_file=cert_path, tls_key_file=key_path)
    assert secure.tls_enabled is True


def test_tls_settings_come_from_the_environment(
    cert_pair: tuple[Path, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    cert_path, key_path = cert_pair
    monkeypatch.setenv("TLS_CERT_FILE", str(cert_path))
    monkeypatch.setenv("TLS_KEY_FILE", str(key_path))
    monkeypatch.setenv("PROXY_HEADERS", "false")
    monkeypatch.setenv("FORWARDED_ALLOW_IPS", "10.0.0.5,172.16.0.0/12")
    settings = Settings(_env_file=None, engine="fake")
    assert settings.tls_enabled is True
    assert settings.proxy_headers is False
    assert settings.forwarded_allow_ips == "10.0.0.5,172.16.0.0/12"


@pytest.mark.skipif(os.name != "posix", reason="file modes are a POSIX concept")
def test_group_or_world_readable_key_logs_a_warning(
    cert_pair: tuple[Path, Path], caplog: pytest.LogCaptureFixture
) -> None:
    cert_path, key_path = cert_pair
    key_path.chmod(0o644)
    with caplog.at_level(logging.WARNING, logger="lenguaraz.config"):
        Settings(_env_file=None, engine="fake", tls_cert_file=cert_path, tls_key_file=key_path)
    assert "readable by group/others" in caplog.text
    caplog.clear()
    key_path.chmod(0o600)
    with caplog.at_level(logging.WARNING, logger="lenguaraz.config"):
        Settings(_env_file=None, engine="fake", tls_cert_file=cert_path, tls_key_file=key_path)
    assert "readable by group/others" not in caplog.text


# ------------------------------------------------------- FR-013-01/02: uvicorn wiring (serve)


def test_build_uvicorn_kwargs_plain_http() -> None:
    settings = Settings(_env_file=None, engine="fake")
    kwargs = build_uvicorn_kwargs(settings, host="0.0.0.0", port=8000)
    assert kwargs == {
        "host": "0.0.0.0",
        "port": 8000,
        "log_config": None,
        "proxy_headers": True,
        "forwarded_allow_ips": "127.0.0.1,::1",
    }
    with_reload = build_uvicorn_kwargs(settings, host="127.0.0.1", port=8000, reload=True)
    assert with_reload["reload"] is True
    assert with_reload["reload_dirs"] == ["lenguaraz"]


def test_build_uvicorn_kwargs_with_tls_and_proxy(cert_pair: tuple[Path, Path]) -> None:
    cert_path, key_path = cert_pair
    settings = Settings(
        _env_file=None,
        engine="fake",
        tls_cert_file=cert_path,
        tls_key_file=key_path,
        tls_ca_file=cert_path,  # any PEM bundle; here the certificate itself
        proxy_headers=False,
        forwarded_allow_ips="*",
    )
    kwargs = build_uvicorn_kwargs(settings, host="0.0.0.0", port=8443)
    assert kwargs["ssl_certfile"] == str(cert_path)
    assert kwargs["ssl_keyfile"] == str(key_path)
    assert kwargs["ssl_ca_certs"] == str(cert_path)
    assert kwargs["proxy_headers"] is False
    assert kwargs["forwarded_allow_ips"] == "*"
    assert "reload" not in kwargs
    # every key is a real uvicorn.Config parameter
    uvicorn.Config("lenguaraz.api.app:build", factory=True, **kwargs)


def test_serve_passes_the_tls_kwargs_and_logs_the_scheme(
    cert_pair: tuple[Path, Path], monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture
) -> None:
    cert_path, key_path = cert_pair
    calls: dict[str, object] = {}

    def fake_run(app: object, **kwargs: object) -> None:
        calls["app"] = app
        calls.update(kwargs)

    monkeypatch.setattr(uvicorn, "run", fake_run)
    monkeypatch.setattr(cli, "configure_logging", lambda level: None)  # keep caplog's handler
    monkeypatch.chdir(ROOT)
    monkeypatch.setenv("ENGINE", "fake")
    monkeypatch.setenv("STAGES_FILE", "examples/stages.minimal.yaml")
    monkeypatch.setenv("TLS_CERT_FILE", str(cert_path))
    monkeypatch.setenv("TLS_KEY_FILE", str(key_path))
    with caplog.at_level(logging.INFO, logger="lenguaraz.cli"):
        assert cli.main(["serve", "--host", "127.0.0.1", "--port", "8443"]) == 0
    assert calls["port"] == 8443
    assert calls["ssl_certfile"] == str(cert_path)
    assert calls["ssl_keyfile"] == str(key_path)
    assert "https://127.0.0.1:8443" in caplog.text
    assert "wss" in caplog.text


# ------------------------------------------------- AC-1: HTTPS + WSS served by the process


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


async def test_https_healthz_and_wss_captions_in_process(
    cert_pair: tuple[Path, Path], tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.chdir(ROOT)  # the example stage points at samples/ relative to the repo root
    cert_path, key_path = cert_pair
    settings = Settings(
        _env_file=None, engine="fake", tls_cert_file=cert_path, tls_key_file=key_path
    )
    app = create_app(
        settings,
        StagesFile.load(Path("examples/stages.minimal.yaml")),
        engine=FakeSttEngine(),
        web_dist=tmp_path,
    )
    port = _free_port()
    config = uvicorn.Config(app, **build_uvicorn_kwargs(settings, host="127.0.0.1", port=port))
    server = uvicorn.Server(config)
    serving = asyncio.create_task(server.serve())
    try:
        deadline = time.monotonic() + 10
        while not server.started:
            if serving.done():
                serving.result()  # surfaces the startup error
            assert time.monotonic() < deadline, "uvicorn did not start within 10 s"
            await asyncio.sleep(0.05)

        async with httpx.AsyncClient(verify=False, timeout=5) as client:
            response = await client.get(f"https://127.0.0.1:{port}/healthz")
        body = response.json()
        assert body["status"] == "ok"
        assert body["tls"] is True

        insecure = ssl.create_default_context()
        insecure.check_hostname = False
        insecure.verify_mode = ssl.CERT_NONE
        async with connect(f"wss://127.0.0.1:{port}/ws/main?lang=en", ssl=insecure) as socket_:
            first = parse_event(await asyncio.wait_for(socket_.recv(), 5))
        assert isinstance(first, StatusEvent)
        assert first.stage_id == "main"
    finally:
        server.should_exit = True
        await asyncio.wait_for(serving, 15)
